version: "3"

services:
    game:
        image: yeka/python:splendor
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
            - ./client:/client
        working_dir: /
        command: python /server/splendor.py
